TOKEN = "YOUR BOT TOKEN"

MODERATION = ["MODERATION ROLE ID"]

VOICE_MUTE_ID = "VOIS MUT ROLE ID"

TEXT_MUTE_ID = "TEXT MUT ROLE ID"

CHANNEL_LOG_ID = "LOG CHANNEL ID"

LOCAL_BAN_ID = "ROLE ID LOCAL BAN"